### ISSUE TITLE
Can't resolve './cradleLoader.css'

### ISSUE THREAD

**Issue by kabbagepatch** [mhnpd/Test#120]
Getting this error when I installed the latest version and imported the react-spinner-loader.css file. My app was just made using create-react-app and has no other custom stuff

I did notice this was a very recent change to change the filenames from CradleLoader.css to cradleLoader.css without changing the imports. Was there a reason for that change? It is possible, since I'm using a Mac, that the change throws an error for me, while for someone using a Windows device, the issue won't show

```
Failed to compile.

./node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css)
Cannot find file: 'cradleLoader.css' does not match the corresponding name on disk: './node_modules/react-loader-spinner/dist/loader/css/CradleLoader.css'.

```

**Comment by murtuzaalisurti** [comment]
> Getting this error when I installed the latest version and imported the react-spinner-loader.css file. My app was just made using create-react-app and has no other custom stuff
> 
> I did notice this was a very recent change to change the filenames from CradleLoader.css to cradleLoader.css without changing the imports. Was there a reason for that change? It is possible, since I'm using a Mac, that the change throws an error for me, while for someone using a Windows device, the issue won't show
> 
> ```
> Failed to compile.
> 
> ./node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css)
> Cannot find file: 'cradleLoader.css' does not match the corresponding name on disk: './node_modules/react-loader-spinner/dist/loader/css/CradleLoader.css'.
> ```

I am having the same issue!

**Comment by mhnpd** [comment]
Fixed with v5.1.2

**Comment by ugputu18** [comment]
Version 5.1.2 has the same error. Last working version is 5.1.0

**Comment by mhnpd** [comment]
Looks like there is still an issue and I have a proposal to remove css entirely for the library.

Having the css files in the project is already causing a lot of issue in multiple environment and I am think of removing it from project and using `css-in-js` library to maintain the css.  This will allow us support SVG as well as CSS base loader without having css files and ready to use exports.

**Comment by devartkr** [comment]
This import will eliminate the error.
import "react-loader-spinner/dist/loader/css/CradleLoader.css";
import "react-loader-spinner/dist/loader/css/Plane.css";
import "react-loader-spinner/dist/loader/css/Triangle.css";

**Comment by abhi-laksh** [comment]
> This import will eliminate the error. import "react-loader-spinner/dist/loader/css/CradleLoader.css"; import "react-loader-spinner/dist/loader/css/Plane.css"; import "react-loader-spinner/dist/loader/css/Triangle.css";

This is not working when I am using react with webpack. The errors are :

> Module not found: Error: Package path ./dist/loader/css/Plane.css is not exported from package <path_to_project>/node_modules/react-loader-spinner

> Module not found: Error: Package path ./dist/loader/css/Triangle.css is not exported from package <path_to_project>/node_modules/react-loader-spinner

> Module not found: Error: Package path ./dist/loader/css/CradleLoader.css is not exported from package <path_to_project>/node_modules/react-loader-spinner

**Comment by shivang-9357** [comment]
FIXED 100% !!!!!!
The problem is in 

> ../node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css

Here the imports are misspelled. Just change it from:

```
@import"./cradleLoader.css";
@import"./plane.css";
@import"./triangle.css";
```

to
```
@import"./CradleLoader.css";
@import"./Plane.css";
@import"./Triangle.css";
```
Just make the names the same as the file names in the same folder.

**Comment by gamer-1478** [comment]
Running Into The Same Errors As Everyone Here, @shivang-9357 's Fix Works For Me Locally. I guess consider opening a pr or smth.

**Comment by utecht** [comment]
The problem is that the changed filenames were not included in the package. I just made a local version of a "5.1.3" that merely bumped the version number again, and that solved this problem when using the code from the master branch.

**Comment by mhnpd** [comment]
#121 fixes this issue

**Comment by tarik56** [comment]
**EDIT:**  Package was just updated when I wrote this Issue, I can confirm, Version 5.1.3 fixxes this issue

I'm using Version 5.1.2

I have only the two imports in my project:
```
import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";
import {Audio, Triangle} from "react-loader-spinner";
```

I still get the Error:

```
./node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-loader-spinner/dist/loader/css/reac
t-spinner-loader.css)
Cannot find file: 'cradleLoader.css' does not match the corresponding name on disk: '.\node_modules\react-loader-spinner\dist\loader\css\CradleLoader.css'
```

**Comment by mhnpd** [comment]
> I'm using Version 5.1.2
> 
> I have only the two imports in my project:
> 
> ```
> import "react-loader-spinner/dist/loader/css/react-spinner-loader.css";
> import {Audio, Triangle} from "react-loader-spinner";
> ```
> 
> I still get the Error:
> 
> ```
> ./node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css (./node_modules/css-loader/dist/cjs.js??ref--5-oneOf-4-1!./node_modules/postcss-loader/src??postcss!./node_modules/react-loader-spinner/dist/loader/css/reac
> t-spinner-loader.css)
> Cannot find file: 'cradleLoader.css' does not match the corresponding name on disk: '.\node_modules\react-loader-spinner\dist\loader\css\CradleLoader.css'
> ```

Please use higer version v5.1.3

**Comment by tarik56** [comment]
updated comment.

Version 5.1.3 works fine, thanks !

**Comment by shivang-9357** [comment]
> FIXED 100% !!!!!! The problem is in
> 
> > ../node_modules/react-loader-spinner/dist/loader/css/react-spinner-loader.css
> 
> Here the imports are misspelled. Just change it from:
> 
> ```
> @import"./cradleLoader.css";
> @import"./plane.css";
> @import"./triangle.css";
> ```
> 
> to
> 
> ```
> @import"./CradleLoader.css";
> @import"./Plane.css";
> @import"./Triangle.css";
> ```
> 
> Just make the names the same as the file names in the same folder.

This fix will not work anymore in the latest version 5.1.3
Just install the latest version and it will work fine w/o any modifications.
